### PR TITLE
fix: generate new sea-orm entites and update services

### PR DESCRIPTION
**Pull request by fan-tastic-z**
generate new sea-orm entites and update serivces code, now use salvo-cli with sea-orm generate code is success

### CODE REVIEW

**Comment by fankaiLiu** [comment]
The code generated with options   **WebSite Sqlite Sqlx**   for the cargo check did not run successfully. Can you help check why?

**Comment by fan-tastic-z** [comment]
> The code generated with options **WebSite Sqlite Sqlx** for the cargo check did not run successfully. Can you help check why?

ok ,let me see

**Comment by fankaiLiu** [comment]
I found the problem. I'll fix him. :)

**Comment by fankaiLiu** [comment]
fixed in https://github.com/salvo-rs/salvo-cli/commit/135d0683b0e289c148c31d0ae8e2694502072a03  :)

**Comment by fan-tastic-z** [comment]
> I found the problem. I'll fix him. :)

ok, I was about to submit a PR just now and found that you had already fixed it.

**Pull request merged**
